### ISSUE TITLE
Rename DEVICE_SERIAL_STORE to RPI_DEVICE_SERIAL_STORE

### ISSUE THREAD

**Issue by Siecje** [raspberrypi/rpi-sb-provisioner#34]
`/etc/rpi-sb-provisioner/config` contains `DEVICE_SERIAL_STORE=/usr/local/etc/rpi-sb-provisioner/seen`

The README lists the config option as `RPI_DEVICE_SERIAL_STORE`.

**Comment by tdewey-rpi** [comment]
Great catch, @Siecje.

Expect a PR today.
