### ISSUE TITLE
Support for Compute Module 5?

### ISSUE THREAD

**Issue by mattjudge** [raspberrypi/rpi-sb-provisioner#89]
The docs mention support for provisioning Compute Module 4, and Raspberry Pi 5, but I can't see any explicit mention of Compute Module 5 - is this already supported / on the roadmap?

Thanks!

**Comment by tdewey-rpi** [comment]
Supported, with the exception of PKCS11 signing keys - which requires a later change.

I've been happy using this tool on CM5 on my desk.

Docs will be updated later this week.

**Comment by mattjudge** [comment]
That's great to hear, thanks for the quick response!

**Comment by torntrousers** [comment]
> Supported, with the exception of PKCS11 signing keys - which requires a later change.

looking forward to that fix...
